#source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/CainLuo/CLPodSpec.git'

use_frameworks!
platform :ios, '10.0'

target 'CLTools_Example' do
  pod 'CLTools', :path => '../'
  
#  pod 'SwifterSwift'
#  pod 'Localize-Swift'
  
  # Localize
#  pod 'Localize-Swift' # https://github.com/marmelroy/Localize-Swift
  
  # Tools
#  pod 'SwifterSwift' # https://github.com/SwifterSwift/SwifterSwift

  target 'CLTools_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
